#!/usr/bin/env node

/**
 * Generate a markdown report from style regression test results.
 * Usage: node tests/style-regression/generate-report.js
 */

const fs = require('fs');
const path = require('path');

const RESULTS_FILE = path.join(__dirname, 'results.json');
const REPORT_FILE = path.join(__dirname, 'regression-report.md');

function classifyScore(score) {
  if (score === undefined) return { label: 'SKIP', icon: '-' };
  if (score >= 80) return { label: 'PASS', icon: '+' };
  if (score >= 60) return { label: 'WARN', icon: '~' };
  return { label: 'FAIL', icon: '!' };
}

function generateReport() {
  if (!fs.existsSync(RESULTS_FILE)) {
    console.error('No results.json found. Run the tests first:');
    console.error('  npx playwright test');
    process.exit(1);
  }

  const results = JSON.parse(fs.readFileSync(RESULTS_FILE, 'utf-8'));
  const now = new Date().toISOString().slice(0, 19).replace('T', ' ');

  // Group by viewport
  const byViewport = {};
  for (const r of results) {
    if (!byViewport[r.viewport]) byViewport[r.viewport] = [];
    byViewport[r.viewport].push(r);
  }

  // Summary stats
  const scored = results.filter((r) => r.similarity !== undefined);
  const avgSimilarity = scored.length
    ? Math.round((scored.reduce((s, r) => s + r.similarity, 0) / scored.length) * 100) / 100
    : 0;
  const passing = scored.filter((r) => r.similarity >= 80).length;
  const warnings = scored.filter((r) => r.similarity >= 60 && r.similarity < 80).length;
  const failing = scored.filter((r) => r.similarity < 60).length;
  const skipped = results.filter((r) => r.similarity === undefined).length;

  let md = '# Style Regression Report\n\n';
  md += `**Generated:** ${now}\n`;
  md += `**Pages tested:** ${results.length} (${scored.length} compared, ${skipped} skipped)\n`;
  md += `**Average similarity:** ${avgSimilarity}%\n\n`;

  md += '## Summary\n\n';
  md += '| Metric | Count |\n';
  md += '|--------|-------|\n';
  md += `| PASS (>=80%) | ${passing} |\n`;
  md += `| WARN (60-79%) | ${warnings} |\n`;
  md += `| FAIL (<60%) | ${failing} |\n`;
  md += `| SKIP (error) | ${skipped} |\n\n`;

  for (const [viewport, vpResults] of Object.entries(byViewport)) {
    md += `## ${viewport.charAt(0).toUpperCase() + viewport.slice(1)} (${viewport === 'desktop' ? '1440px' : '375px'})\n\n`;
    md += '| Template | Page | Similarity | Status |\n';
    md += '|----------|------|------------|--------|\n';

    // Sort by similarity ascending (worst first)
    const sorted = [...vpResults].sort((a, b) => (a.similarity ?? -1) - (b.similarity ?? -1));

    for (const r of sorted) {
      const { label } = classifyScore(r.similarity);
      const slug = r.edsPath.replace(/\//g, '_').replace(/^_/, '') || 'index';
      const sim = r.similarity !== undefined ? `${r.similarity}%` : 'N/A';
      const error = r.originalError || r.edsError || '';
      const note = error ? ` (${error.slice(0, 50)})` : '';
      md += `| ${r.template} | ${slug} | ${sim} | ${label}${note} |\n`;
    }
    md += '\n';
  }

  // Detail section for failures
  const failures = scored.filter((r) => r.similarity < 60);
  if (failures.length > 0) {
    md += '## Pages Needing Attention\n\n';
    for (const r of failures) {
      const slug = r.edsPath.replace(/\//g, '_').replace(/^_/, '') || 'index';
      md += `### ${r.viewport}/${r.template}/${slug}\n`;
      md += `- **Original:** ${r.url}\n`;
      md += `- **EDS path:** ${r.edsPath}\n`;
      md += `- **Similarity:** ${r.similarity}%\n`;
      md += `- **Diff pixels:** ${r.diffPixels.toLocaleString()} / ${r.totalPixels.toLocaleString()}\n`;
      md += `- **Diff image:** \`${path.relative(path.dirname(REPORT_FILE), r.diffPath)}\`\n\n`;
    }
  }

  md += '---\n*Generated by style-regression test suite*\n';

  fs.writeFileSync(REPORT_FILE, md);
  console.log(`Report written to ${REPORT_FILE}`);
  console.log(`  ${passing} pass, ${warnings} warn, ${failing} fail, ${skipped} skip`);
  console.log(`  Average similarity: ${avgSimilarity}%`);
}

generateReport();
